LABELS_TO_IDS = {
    "h": 0,
    "a": 1,
    "c": 2,
    "s": 3,
    "u": 4,
    "d": 5,
    "f": 6,
    "n": 7,
    }
LABELS_TO_IDS_EMOSPEECH = {
    "n": 0,
    "d": 1,
    "a": 2,
    "s": 3,
    "h": 4,
    "f": 5,
    }
LABELS_TO_IDS ={
    "lvPPA": 0,
    "nfPPA": 1,
    "svPPA": 2,
}
TRAIN_DEFAULT_SETTINGS = {
    'csv_path': '/home/usuaris/veussd/roger.esteve.sanchez/WAB_samples/labels.csv',
    'train_labels_path' : './labels/training_labels.tsv',
    'validation_labels_path' : './labels/development_labels.tsv',
    'dataset_transcriptions_path': './labels/dataset_transcriptions.tsv',
    'model_output_folder' : './models/',
    'log_file_folder' : './logs/train/',
    'sample_rate': 16000,
    'training_random_crop_secs' : 2.0,
    'evaluation_random_crop_secs' : 2.0,
    'num_workers' : 0,
    'training_augmentation_prob' : 0.75,
    'evaluation_augmentation_prob' : 0,
    'augmentation_window_size_secs' : 2.0,
    'speech_feature_extractor': 'WAV2VEC2_XLSR_300M',
    'speech_feature_extractor_output_vectors_dimension' : 1024,
    'text_feature_extractor' : 'BERT_LARGE_UNCASED',
    'text_feature_extractor_output_vectors_dimension' : 1024,
    'speech_adapter': 'NoneAdapter',
    'text_adapter': 'NoneAdapter',
    'seq_to_seq_method' : 'NoneSeqToSeq',
    'seq_to_one_method' : 'StatisticalPooling',
    'seq_to_seq_input_dropout' : 0,
    'seq_to_one_input_dropout': 0,
    'classifier_layer_drop_out' : 0,
    'classifier_hidden_layers': 2,
    'classifier_hidden_layers_width': 512,
    'number_classes' : 8,
    'max_epochs' : 50,
    'training_batch_size' : 32,
    'evaluation_batch_size' : 1,
    'eval_and_save_best_model_every' : 1000,
    'print_training_info_every' : 100,
    'early_stopping' : 25,
    'load_checkpoint' : False,
    'optimizer' : 'adam',
    'learning_rate' : 0.0001,
    'learning_rate_multiplier' : 0.5,
    'weight_decay' : 0.001,
    'update_optimizer_every' : 10,
    'loss' : 'CrossEntropy',
    'weighted_loss' : True,
    'use_weights_and_biases' : False,
    'skip_connections' : False
}

